#Uses of String Operators 
a=" Ahaan sah " 
print("Lenght of String :",len(a)) 
print("Minumum word of String :", min(a)) 
print("Maximum word of String :",max(a)) 
print("UpperCase of String :",a.upper()) 
print("LowerCase of String :",a.lower()) 
print("is the string in UpperCase :",a.isupper()) 
print("is the string in LowerCase :",a.islower()) 
print("String Starts form g : ",a.startswith('g')) 
print("String End with a:",a.endswith('a')) 
print("Find o in String :",a.find('o')) 
print("Replace g with Z on string :",a.replace('g','Z')) 
print("Split form d :",a.split('d')) 
print("Partation form i",a.partition('i')) 
print("check digits in string:",a.isdigit()) 
print("Uppercase the 1st leter of word :",a.title()) 
print("check the 1st leter of word ia capital or not:",a.istitle()) 
print("To capitalize the string :",a.capitalize()) 
print("To check the string is start with alphabet or not :",a.isalpha()) 
print("To check the string is start with number or not :",a.isalnum()) 
print("To lstrip the string :",a.lstrip())
print("To rstrip the string :",a.rstrip()) 
print("To strip the string :",a.strip())